### PR TITLE
Json parse exception due to missing ,

### PR DESCRIPTION
**Pull request by DMeloni**
Missing ','

### CODE REVIEW

**Comment by polyfractal** [comment]
Thanks for the PR!  

Could you sign the [Elasticsearch CLA](http://www.elasticsearch.org/contributor-agreement/) so we can merge this?

**Comment by polyfractal** [comment]
Oops, sorry... I went ahead and merged #315 since that CLA was already signed.

But if you go ahead and sign the CLA anyway, we can immediately merge any future PRs.  Thanks again for contributing!

**Comment by DMeloni** [comment]
I just signed. 
Thx for this amazing search engine. (I practiced Solr 2 years and ES is really more powerful)

**Comment by polyfractal** [comment]
Thanks!  Glad you are enjoying Elasticsearch...don't hesitate to open more PRs if you find typos (or things that are unclear) :)

**Pull request closed without merging**
